import type { Idl } from "@coral-xyz/anchor";

/**
 * Anchor IDL for the eurc_vault program (Anchor 0.30.1 format).
 *
 * Hand-written from the Rust source. Once `anchor build` produces a JSON IDL,
 * import that instead.
 */
export const IDL: EurcVault = {
  address: "EVau1tHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
  metadata: {
    name: "eurc_vault",
    version: "0.1.0",
    spec: "0.1.0",
    description: "EURC staking vault on Solana",
  },
  instructions: [
    {
      name: "initialize_vault",
      discriminator: [48, 191, 163, 44, 71, 129, 63, 164],
      accounts: [
        { name: "authority", writable: true, signer: true },
        { name: "vault_config", writable: true },
        { name: "vault_authority" },
        { name: "eurc_mint" },
        { name: "vault_token_account", writable: true },
        { name: "system_program", address: "11111111111111111111111111111111" },
        { name: "token_program", address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
        { name: "associated_token_program", address: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" },
        { name: "rent", address: "SysvarRent111111111111111111111111111111111" },
      ],
      args: [
        { name: "vault_id", type: "u64" },
        { name: "max_capacity", type: "u64" },
        { name: "epoch_duration", type: "i64" },
        { name: "withdrawal_cooldown", type: "i64" },
      ],
    },
    {
      name: "deposit",
      discriminator: [242, 35, 198, 137, 82, 225, 242, 182],
      accounts: [
        { name: "user", writable: true, signer: true },
        { name: "vault_config", writable: true },
        { name: "user_stake", writable: true },
        { name: "vault_authority" },
        { name: "vault_token_account", writable: true },
        { name: "user_token_account", writable: true },
        { name: "token_program", address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
        { name: "system_program", address: "11111111111111111111111111111111" },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "initiate_withdrawal",
      discriminator: [69, 216, 131, 74, 114, 122, 38, 112],
      accounts: [
        { name: "user", signer: true },
        { name: "vault_config" },
        { name: "user_stake", writable: true },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "complete_withdrawal",
      discriminator: [107, 98, 134, 131, 74, 120, 174, 121],
      accounts: [
        { name: "user", writable: true, signer: true },
        { name: "vault_config", writable: true },
        { name: "user_stake", writable: true },
        { name: "vault_authority" },
        { name: "vault_token_account", writable: true },
        { name: "user_token_account", writable: true },
        { name: "token_program", address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
      ],
      args: [],
    },
    {
      name: "cancel_withdrawal",
      discriminator: [183, 104, 181, 250, 28, 128, 210, 70],
      accounts: [
        { name: "user", signer: true },
        { name: "vault_config" },
        { name: "user_stake", writable: true },
      ],
      args: [],
    },
    {
      name: "claim_rewards",
      discriminator: [4, 144, 132, 71, 116, 23, 151, 80],
      accounts: [
        { name: "user", writable: true, signer: true },
        { name: "vault_config", writable: true },
        { name: "user_stake", writable: true },
        { name: "vault_authority" },
        { name: "vault_token_account", writable: true },
        { name: "user_token_account", writable: true },
        { name: "token_program", address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
      ],
      args: [],
    },
    {
      name: "fund_rewards",
      discriminator: [114, 64, 163, 112, 175, 167, 19, 121],
      accounts: [
        { name: "authority", writable: true, signer: true },
        { name: "vault_config", writable: true },
        { name: "vault_authority" },
        { name: "vault_token_account", writable: true },
        { name: "funder_token_account", writable: true },
        { name: "token_program", address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "advance_epoch",
      discriminator: [93, 138, 234, 218, 241, 230, 132, 38],
      accounts: [
        { name: "authority", writable: true, signer: true },
        { name: "vault_config", writable: true },
        { name: "epoch_snapshot", writable: true },
        { name: "system_program", address: "11111111111111111111111111111111" },
      ],
      args: [],
    },
    {
      name: "update_vault_config",
      discriminator: [122, 3, 21, 222, 158, 255, 238, 157],
      accounts: [
        { name: "authority", signer: true },
        { name: "vault_config", writable: true },
      ],
      args: [
        { name: "new_max_capacity", type: { option: "u64" } },
        { name: "new_epoch_duration", type: { option: "i64" } },
        { name: "new_withdrawal_cooldown", type: { option: "i64" } },
      ],
    },
    {
      name: "toggle_pause",
      discriminator: [238, 237, 206, 27, 255, 95, 123, 229],
      accounts: [
        { name: "authority", signer: true },
        { name: "vault_config", writable: true },
      ],
      args: [],
    },
    {
      name: "initiate_authority_transfer",
      discriminator: [210, 43, 101, 215, 119, 140, 106, 218],
      accounts: [
        { name: "authority", signer: true },
        { name: "vault_config", writable: true },
      ],
      args: [{ name: "new_authority", type: "pubkey" }],
    },
    {
      name: "accept_authority_transfer",
      discriminator: [239, 248, 177, 2, 206, 97, 46, 255],
      accounts: [
        { name: "new_authority", signer: true },
        { name: "vault_config", writable: true },
      ],
      args: [],
    },
    {
      name: "emergency_withdraw",
      discriminator: [239, 45, 203, 64, 150, 73, 218, 92],
      accounts: [
        { name: "user", writable: true, signer: true },
        { name: "vault_config", writable: true },
        { name: "user_stake", writable: true },
        { name: "vault_authority" },
        { name: "vault_token_account", writable: true },
        { name: "user_token_account", writable: true },
        { name: "token_program", address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
      ],
      args: [],
    },
  ],
  accounts: [
    { name: "VaultConfig", discriminator: [99, 86, 43, 216, 184, 102, 119, 77] },
    { name: "UserStake", discriminator: [102, 53, 163, 107, 9, 138, 87, 153] },
    { name: "EpochSnapshot", discriminator: [45, 169, 145, 50, 103, 29, 220, 244] },
  ],
  events: [
    { name: "VaultInitialized", discriminator: [180, 43, 207, 2, 18, 71, 3, 75] },
    { name: "Deposited", discriminator: [111, 141, 26, 45, 161, 35, 100, 57] },
    { name: "WithdrawalInitiated", discriminator: [7, 15, 85, 106, 238, 220, 97, 161] },
    { name: "WithdrawalCompleted", discriminator: [190, 43, 125, 91, 115, 50, 166, 172] },
    { name: "WithdrawalCancelled", discriminator: [119, 175, 207, 80, 186, 237, 229, 9] },
    { name: "RewardsClaimed", discriminator: [75, 98, 88, 18, 219, 112, 88, 121] },
    { name: "RewardsFunded", discriminator: [84, 233, 245, 203, 228, 147, 165, 92] },
    { name: "EpochAdvanced", discriminator: [41, 220, 14, 123, 117, 70, 117, 157] },
    { name: "VaultConfigUpdated", discriminator: [72, 22, 37, 111, 58, 30, 160, 212] },
  ],
  errors: [
    { code: 6000, name: "VaultPaused", msg: "Vault is paused -- deposits are disabled" },
    { code: 6001, name: "VaultCapacityExceeded", msg: "Vault has reached maximum capacity" },
    { code: 6002, name: "DepositTooSmall", msg: "Deposit amount is below the minimum" },
    { code: 6003, name: "ZeroDeposit", msg: "Deposit amount is zero" },
    { code: 6004, name: "InsufficientBalance", msg: "Withdrawal amount exceeds deposited balance" },
    { code: 6005, name: "ZeroWithdrawal", msg: "Withdrawal amount is zero" },
    { code: 6006, name: "WithdrawalCooldownActive", msg: "Withdrawal is still in cooldown period" },
    { code: 6007, name: "NoPendingWithdrawal", msg: "No pending withdrawal to complete" },
    { code: 6008, name: "NoPendingWithdrawalToCancel", msg: "No pending withdrawal to cancel" },
    { code: 6009, name: "WithdrawalAlreadyPending", msg: "User already has a pending withdrawal" },
    { code: 6010, name: "NoRewardsToClaim", msg: "No rewards to claim" },
    { code: 6011, name: "ZeroRewardFund", msg: "Reward fund amount is zero" },
    { code: 6012, name: "EpochNotEnded", msg: "Epoch has not ended yet" },
    { code: 6013, name: "InvalidEpochNumber", msg: "Invalid epoch number" },
    { code: 6014, name: "Unauthorized", msg: "Unauthorized -- caller is not the vault authority" },
    { code: 6015, name: "InvalidMint", msg: "Invalid EURC mint address" },
    { code: 6016, name: "MathOverflow", msg: "Arithmetic overflow in reward calculation" },
    { code: 6017, name: "InvalidConfig", msg: "Invalid vault configuration parameter" },
    { code: 6018, name: "CapacityBelowDeposits", msg: "Vault capacity must be greater than total deposits" },
    { code: 6019, name: "NoAuthorityTransferPending", msg: "Authority transfer not initiated" },
    { code: 6020, name: "NotPendingAuthority", msg: "Caller is not the pending authority" },
    { code: 6021, name: "InvalidEpochDuration", msg: "Epoch duration must be positive" },
  ],
  types: [
    {
      name: "VaultConfig",
      type: {
        kind: "struct",
        fields: [
          { name: "vault_id", type: "u64" },
          { name: "authority", type: "pubkey" },
          { name: "pending_authority", type: "pubkey" },
          { name: "eurc_mint", type: "pubkey" },
          { name: "bump", type: "u8" },
          { name: "authority_bump", type: "u8" },
          { name: "paused", type: "bool" },
          { name: "max_capacity", type: "u64" },
          { name: "total_deposits", type: "u64" },
          { name: "total_rewards_distributed", type: "u64" },
          { name: "accumulated_reward_per_share", type: "u128" },
          { name: "current_epoch", type: "u64" },
          { name: "epoch_duration", type: "i64" },
          { name: "epoch_start_time", type: "i64" },
          { name: "withdrawal_cooldown", type: "i64" },
          { name: "staker_count", type: "u64" },
          { name: "_reserved", type: { array: ["u8", 128] } },
        ],
      },
    },
    {
      name: "UserStake",
      type: {
        kind: "struct",
        fields: [
          { name: "vault", type: "pubkey" },
          { name: "user", type: "pubkey" },
          { name: "bump", type: "u8" },
          { name: "deposited_amount", type: "u64" },
          { name: "reward_debt", type: "u128" },
          { name: "total_rewards_claimed", type: "u64" },
          { name: "pending_withdrawal_amount", type: "u64" },
          { name: "withdrawal_available_at", type: "i64" },
          { name: "first_deposit_time", type: "i64" },
          { name: "last_interaction_time", type: "i64" },
          { name: "_reserved", type: { array: ["u8", 64] } },
        ],
      },
    },
    {
      name: "EpochSnapshot",
      type: {
        kind: "struct",
        fields: [
          { name: "vault", type: "pubkey" },
          { name: "epoch_number", type: "u64" },
          { name: "bump", type: "u8" },
          { name: "total_deposits", type: "u64" },
          { name: "total_rewards_distributed", type: "u64" },
          { name: "accumulated_reward_per_share", type: "u128" },
          { name: "staker_count", type: "u64" },
          { name: "start_time", type: "i64" },
          { name: "end_time", type: "i64" },
          { name: "_reserved", type: { array: ["u8", 64] } },
        ],
      },
    },
  ],
};

export type EurcVault = Idl;
