[package]
name = "eurc-vault"
version = "0.1.0"
description = "EURC epoch-based staking vault on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "eurc_vault"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
anchor-spl = "0.30.1"
